from os.path import join
from glob import glob
from bids import BIDSLayout

configfile: "config/config.yml"


# bids_dir  set in json file.
# can also override at command-line with e.g.:  --config bids_dir='path/to/dir'  or --configfile ...
input_dir = config['input_dir']
output_dir = config['output_dir']
entities = config['entities']
entities_afids = config['entities_afids']

layout = BIDSLayout(input_dir, validate=False)
subjects = layout.get_subjects(**entities)
sessions = layout.get_sessions(**entities)
runs = layout.get_runs(**entities)

if len(sessions) > 0:
    subj_sess_dir = join('sub-{subject}','ses-{session}')
    subj_sess_prefix = 'sub-{subject}_ses-{session}'
else:
    subj_sess_dir = 'sub-{subject}'
    subj_sess_prefix = 'sub-{subject}'

# Max number of runs in lhsc is 1 so hard code 01
if len(runs) > 0:
    subj_sess_prefix += '_run-01'

datatype = entities['datatype']
suffix = '_' + entities['suffix'] + entities['ext']

datatype_afids = entities_afids['datatype']
suffix_afids = '_' + entities_afids['suffix'] + entities_afids['ext']

rule all:
    input:
        mni_rigid = expand( join(output_dir, 'deriv','mni_space',subj_sess_dir,datatype,subj_sess_prefix + '_space-MNI152NLin2009cAsym' + suffix ), subject=subjects,session=sessions),
        tform_new = expand( join(output_dir, 'deriv','mni_space',subj_sess_dir,datatype,subj_sess_prefix + '_from-T1w_to-MNI152NLin2009cAsym_mode-image_desc-ras_xfm.txt' ), subject=subjects,session=sessions),
        tfm_new = expand( join(output_dir, 'deriv','mni_space',subj_sess_dir,datatype,subj_sess_prefix + '_from-T1w_to-MNI152NLin2009cAsym_mode-image_desc-ras_xfm.tfm' ), subject=subjects,session=sessions),
        fid_mni_rigid = expand( join(output_dir, 'deriv','mni_space',subj_sess_dir,datatype_afids,subj_sess_prefix + '_space-MNI152NLin2009cAsym' + suffix_afids), subject=subjects,session=sessions)

include: 'rules/mniTransform.smk'
