import os
from os.path import join,abspath,basename
from glob import glob
from bids import BIDSLayout
from scripts.commonsmk import bids_name
import shutil

configfile: "config/config.yml"

# Copy dataset_description.json files to deriv directories (for BIDSlayout indexing)
deriv_dirs=[0]
deriv_dirs[0]= mniSpace = join(config['output_dir'],'deriv','mni_space')

for idir in deriv_dirs:
    if not os.path.exists(idir):
        os.makedirs(idir)
    data_des = abspath(join(join(srcdir("script.sh"),"../.."),'resources','dataset_description_'+basename(idir)+'.json'))
    if not os.path.exists(join(idir,'dataset_description.json')):
        shutil.copy2(data_des, join(idir,'dataset_description.json'))

# Load the BIDS directory
layout = BIDSLayout(join(config['input_dir'],'bids'), derivatives=join(config['input_dir'],'deriv'),validate=False)


subjects = layout.get_subjects(**config['meta_nifti'])
sessions = layout.get_sessions(**config['meta_nifti'])
runs = layout.get_runs(**config['meta_nifti'])

suffix = config['meta_nifti']['suffix'] + config['meta_nifti']['extension']
suffix_afids = config['deriv_meta']['afids']['suffix'] + config['deriv_meta']['afids']['extension']

rule all:
    input:
        expand(bids_name(root=join(config['output_dir'],'deriv','mni_space'),kind='anat',subject='{subject}',suffix='registration.done'), subject=subjects),

if basename(config['input_dir']).lower()== 'oasis':
	include: 'rules/mniTransform_withbet.smk'
else:
	include: 'rules/mniTransform.smk'