repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-docstring-first
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      args: [--filter-files]
- repo: https://github.com/psf/black
  rev: 19.3b0
  hooks:
  - id: black
