# Data paths
# Set input as the root directory that contains both */bids and */deriv/afids directories
# NOTE: within the output path a new directory is created called /deriv/mni_space
# thus you can set output anywhere you want, if it's set the same as input then data 
# will be written to deriv
input_dir: /media/veracrypt6/projects/autofids/data/OASIS
output_dir: /media/veracrypt6/projects/autofids/data/OASIS

#template: 'template_align_mni_rigid.nii.gz'
template: 'resources/mni_icbm152_t1_tal_nlin_asym_09c.nii.gz'

meta_nifti:
  suffix: T1w
  extension: .nii.gz
  datatype: anat
  scope: raw

deriv_meta:
  afids:
    suffix: afids
    extension: .fcsv
    datatype: anat
    scope: afids
    desc: average

flirt:
    dof: 6
    coarsesearch: 60
    finesearch: 18
    cost: mutualinfo    # {mutualinfo,corratio,normcorr,normmi,leastsq,labeldiff,bbr}
    interp: sinc        # {trilinear,nearestneighbour,sinc,spline}