# Data paths
# Set input as the root directory that contains both */bids and */deriv/afids directories
# NOTE: within the output path a new directory is created called /deriv/mni_space
# thus you can set output anywhere you want, if it's set the same as input then data 
# will be written to deriv
input_dir: /scratch/dcao6/autofid/data/OASIS
output_dir: /scratch/dcao6/autofid/data/OASIS

#template: 'template_align_mni_rigid.nii.gz'
template: 'resources/mni_icbm152_t1_tal_nlin_asym_09c.nii.gz'

#Set nifti file naming
entities:
  datatype: anat
  suffix: T1w
  ext: .nii.gz

#Set afids file naming
entities_afids:
  datatype: anat
  suffix: afids
  ext: .fcsv
