# Data paths
# Set input as the root directory that contains both */bids and */deriv/afids directories
# NOTE: within the output path a new directory is created called /deriv/mni_space
# thus you can set output anywhere you want, if it's set the same as input then data 
# will be written to deriv
input_dir: /media/veracrypt6/projects/templateProjects/auto_afids/clinical_data
output_dir: /home/greydon/Downloads/autoafids
sqlDatabase: /home/greydon/Documents/GitHub/Auto-afids/resources/subject_data.db

#template: 'template_align_mni_rigid.nii.gz'
template: 'resources/mni_icbm152_t1_tal_nlin_asym_09c.nii.gz'

#Set nifti file naming
entities:
  datatype: anat
  suffix: T1w
  ext: .nii.gz

#Set afids file naming
entities_afids:
  datatype: anat
  suffix: afids
  ext: .fcsv

#Set model training
model_params:
  train_level: fine
  feature_offsets: resources/feature_offsets.npz