#---- begin snakebids boilerplate ----------------------------------------------

import snakebids
from snakebids import bids

from os.path import join

configfile: 'config/snakebids.yml'

#writes inputs_config.yml and updates config dict
config.update(
    snakebids.generate_inputs(
        bids_dir=config["bids_dir"],
        pybids_inputs=config["pybids_inputs"],
        derivatives=config["derivatives"],
        participant_label=config["participant_label"],
        exclude_participant_label=config["exclude_participant_label"]
    )
)



#this adds constraints to the bids naming
wildcard_constraints:  **snakebids.get_wildcard_constraints(\
    config["pybids_inputs"]\
)

#---- end snakebids boilerplate ------------------------------------------------

rule all:
    input:
        expand(
            bids(
                root=join(config["output_dir"], "derivatives", "models"),
                prefix="afid-{afid_num}",
                suffix="model",
                desc="{train_level}",
                space="MNI152NLin2009cAsym",
            ),
            afid_num=[str(num).zfill(2) for num in range(1, 33)],
            train_level=["coarse", "medium", "fine"],
        )

include: "rules/mniTransform.smk"
include: "rules/modelTraining.smk"
