#---- begin snakebids boilerplate ----------------------------------------------

from os.path import join

import snakebids
from snakebids import bids

configfile: 'config/snakebids.yml'

#writes inputs_config.yml and updates config dict
config.update(
    snakebids.generate_inputs(
        bids_dir=config["bids_dir"],
        pybids_inputs=config["pybids_inputs"],
        derivatives=config["derivatives"],
        participant_label=config["participant_label"],
        exclude_participant_label=config["exclude_participant_label"]
    )
)



#this adds constraints to the bids naming
wildcard_constraints:  **snakebids.get_wildcard_constraints(\
    config["pybids_inputs"]\
)

#---- end snakebids boilerplate ------------------------------------------------

rule all:
    input: 
        expand(
            bids(
                root=join(config["output_dir"], "derivatives", "auto-afids"),
                prefix="afid-{afid_num}",
                suffix='afid.txt',
                space="MNI152NLin2009cAsym",
                **config['input_wildcards']['t1w']
            ),
            zip,
            afid_num=[str(num).zfill(2) for num in range(1, 33)],
            **config['input_zip_lists']['t1w']
        )

include: "rules/modelApplication.smk"
